### ISSUE TITLE
How can I get input from the user?

### ISSUE THREAD

**Issue by Quillbert** [adam-mcdaniel/free#6]
See title.

**Comment by adam-mcdaniel** [comment]
It seems that ive forgot to add a builtin function that gets user input. I'll add one within the next day or two.

**Comment by adam-mcdaniel** [comment]
Ive written the fix and I'm creating a PR right now. You can see the code in the `fix/strings_and_input` branch. There's an input example called `input.fr` and more input in `smpl.fr`.

**Comment by adam-mcdaniel** [comment]
Fixed with #8
